# Generated by Django 4.0.2 on 2022-02-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
